# Generated by Django 3.2.13 on 2022-04-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='production_date',
            field=models.IntegerField(blank=True),
        ),
    ]
