# Generated by Django 3.2.13 on 2022-04-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0003_movietype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieType',
            new_name='Category',
        ),
    ]
