# Generated by Django 3.2.13 on 2022-04-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0005_movie_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='drive',
            name='series_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
