# Generated by Django 3.2.13 on 2022-04-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0006_auto_20220429_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='resolution',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
