# Generated by Django 3.2.13 on 2022-04-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0007_drive_resolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drive',
            name='resolution',
        ),
    ]
