# Generated by Django 3.2.13 on 2022-04-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0008_remove_drive_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='production_date',
            field=models.IntegerField(blank=True, default=2022),
        ),
    ]
